// 데모 모드에서 처음 보여줄 맛집 시드 데이터.
// 실제 공유 모드(Firebase)에서는 사용되지 않습니다.
// ratingSum / ratingCount = 사용자들이 매긴 별점의 합계 / 개수.
export const SEED_RESTAURANTS = [
  {
    id: "seed-1",
    name: "성수동 국밥",
    category: "한식",
    menu: "돼지국밥 · 수육백반",
    station: "성수역",
    address: "서울 성동구 성수동",
    lat: 37.5448,
    lng: 127.0561,
    kakaoUrl: "",
    ratingSum: 22,
    ratingCount: 5,
  },
  {
    id: "seed-2",
    name: "뚝섬 부엌",
    category: "한식",
    menu: "제철 정식 · 보리비빔밥",
    station: "뚝섬역",
    address: "서울 성동구 성수동",
    lat: 37.5476,
    lng: 127.0479,
    kakaoUrl: "",
    ratingSum: 23,
    ratingCount: 5,
  },
  {
    id: "seed-3",
    name: "트레일러 파스타",
    category: "양식",
    menu: "트러플 크림 파스타 · 라구",
    station: "뚝섬역",
    address: "서울 성동구 성수동",
    lat: 37.5469,
    lng: 127.0468,
    kakaoUrl: "",
    ratingSum: 18,
    ratingCount: 4,
  },
  {
    id: "seed-4",
    name: "성수 스테이크하우스",
    category: "양식",
    menu: "채끝 스테이크 · 감바스",
    station: "성수역",
    address: "서울 성동구 성수동",
    lat: 37.5452,
    lng: 127.0571,
    kakaoUrl: "",
    ratingSum: 24,
    ratingCount: 5,
  },
  {
    id: "seed-5",
    name: "오마카세 뚝",
    category: "일식",
    menu: "런치 스시 오마카세",
    station: "뚝섬역",
    address: "서울 성동구 성수동",
    lat: 37.5465,
    lng: 127.0481,
    kakaoUrl: "",
    ratingSum: 19,
    ratingCount: 4,
  },
  {
    id: "seed-6",
    name: "멘야 성수",
    category: "일식",
    menu: "돈코츠 라멘 · 차슈동",
    station: "성수역",
    address: "서울 성동구 성수동",
    lat: 37.5441,
    lng: 127.0552,
    kakaoUrl: "",
    ratingSum: 17,
    ratingCount: 4,
  },
  {
    id: "seed-7",
    name: "대림창고 카페",
    category: "카페",
    menu: "핸드드립 · 바스크 치즈케이크",
    station: "성수역",
    address: "서울 성동구 성수동",
    lat: 37.5438,
    lng: 127.0566,
    kakaoUrl: "",
    ratingSum: 18,
    ratingCount: 4,
  },
  {
    id: "seed-8",
    name: "어니언 성수",
    category: "카페",
    menu: "팡도르 · 플랫화이트",
    station: "성수역",
    address: "서울 성동구 성수동",
    lat: 37.5446,
    lng: 127.0558,
    kakaoUrl: "",
    ratingSum: 23,
    ratingCount: 5,
  },
  {
    id: "seed-9",
    name: "뚝섬 포차",
    category: "술집",
    menu: "골뱅이무침 · 모둠전",
    station: "뚝섬역",
    address: "서울 성동구 성수동",
    lat: 37.5474,
    lng: 127.0476,
    kakaoUrl: "",
    ratingSum: 17,
    ratingCount: 4,
  },
  {
    id: "seed-10",
    name: "성수 양조장",
    category: "술집",
    menu: "수제맥주 · 안주 플래터",
    station: "성수역",
    address: "서울 성동구 성수동",
    lat: 37.5455,
    lng: 127.0563,
    kakaoUrl: "",
    ratingSum: 18,
    ratingCount: 4,
  },
];
