// 뚝섬역 근처 맛집 샘플 데이터 (데모용)
const RESTAURANTS = [
  {
    name: "성수동 국밥",
    category: "한식",
    menu: "돼지국밥 · 수육백반",
    rating: 4.5,
    price: "₩9,000",
    walk: 4,
  },
  {
    name: "뚝섬 부엌",
    category: "한식",
    menu: "제철 정식 · 보리비빔밥",
    rating: 4.6,
    price: "₩13,000",
    walk: 6,
  },
  {
    name: "트레일러 파스타",
    category: "양식",
    menu: "트러플 크림 파스타 · 라구",
    rating: 4.4,
    price: "₩16,000",
    walk: 3,
  },
  {
    name: "성수 스테이크하우스",
    category: "양식",
    menu: "채끝 스테이크 · 감바스",
    rating: 4.7,
    price: "₩29,000",
    walk: 8,
  },
  {
    name: "오마카세 뚝",
    category: "일식",
    menu: "런치 스시 오마카세",
    rating: 4.8,
    price: "₩55,000",
    walk: 5,
  },
  {
    name: "멘야 성수",
    category: "일식",
    menu: "돈코츠 라멘 · 차슈동",
    rating: 4.3,
    price: "₩11,000",
    walk: 2,
  },
  {
    name: "대림창고 카페",
    category: "카페",
    menu: "핸드드립 · 바스크 치즈케이크",
    rating: 4.5,
    price: "₩7,000",
    walk: 7,
  },
  {
    name: "어니언 성수",
    category: "카페",
    menu: "팡도르 · 플랫화이트",
    rating: 4.6,
    price: "₩8,500",
    walk: 9,
  },
  {
    name: "뚝섬 포차",
    category: "술집",
    menu: "골뱅이무침 · 모둠전",
    rating: 4.2,
    price: "₩18,000",
    walk: 3,
  },
  {
    name: "성수 양조장",
    category: "술집",
    menu: "수제맥주 · 안주 플래터",
    rating: 4.5,
    price: "₩22,000",
    walk: 6,
  },
  {
    name: "할매 손칼국수",
    category: "한식",
    menu: "바지락 칼국수 · 왕만두",
    rating: 4.4,
    price: "₩8,000",
    walk: 5,
  },
  {
    name: "비스트로 한강",
    category: "양식",
    menu: "리조또 · 하우스 와인",
    rating: 4.5,
    price: "₩19,000",
    walk: 10,
  },
];
